In [1]:
#

In [2]:
import pandas as pd

In [3]:
global ZIP_DF

In [4]:
file_path = '../2_develop_synthetic_company/ZIP_Locale_Detail.xls'

# Read the Excel file into a Pandas DataFrame
ZIP_DF = pd.read_excel(file_path, dtype=str)

# Display the DataFrame
ZIP_DF.head()

,AREA NAME,AREA CODE,DISTRICT NAME,DISTRICT NO,DELIVERY ZIPCODE,LOCALE NAME,PHYSICAL DELV ADDR,PHYSICAL CITY,PHYSICAL STATE,PHYSICAL ZIP,PHYSICAL ZIP 4
0,SOUTHERN,4G,PUERTO RICO,006,00601,ADJUNTAS,37 CALLE MUNOZ RIVERA,ADJUNTAS,PR,00601,9998
1,SOUTHERN,4G,PUERTO RICO,006,00602,AGUADA,5 AVE NATIVO ALERS,AGUADA,PR,00602,9998
2,SOUTHERN,4G,PUERTO RICO,006,00603,AGUADILLA,50 CARR 459 STE 1,AGUADILLA,PR,00603,9998
3,SOUTHERN,4G,PUERTO RICO,006,00604,RAMEY,100 AVE BORINQUEN,AGUADILLA,PR,00603,9996
4,SOUTHERN,4G,PUERTO RICO,006,00605,AGUADILLA,50 CARR 459 STE 1,AGUADILLA,PR,00603,9998

In [5]:
df_sd = ZIP_DF[ZIP_DF['PHYSICAL STATE'] == 'SD']

In [6]:
df_sd.shape

(453, 11)

In [7]:
df_sd['DELIVERY ZIPCODE'].unique()

array(['57001', '57002', '57003', '57004', '57005', '57006', '57010',
       '57012', '57013', '57014', '57015', '57016', '57017', '57018',
       '57020', '57021', '57022', '57024', '57025', '57026', '57027',
       '57028', '57029', '57030', '57031', '57032', '57033', '57034',
       '57035', '57036', '57037', '57038', '57039', '57040', '57041',
       '57042', '57043', '57045', '57046', '57047', '57048', '57049',
       '57050', '57051', '57052', '57053', '57054', '57055', '57057',
       '57058', '57059', '57061', '57062', '57063', '57064', '57065',
       '57066', '57067', '57068', '57069', '57070', '57071', '57072',
       '57073', '57075', '57076', '57077', '57078', '57101', '57103',
       '57104', '57105', '57106', '57107', '57108', '57109', '57110',
       '57117', '57118', '57201', '57212', '57213', '57214', '57216',
       '57217', '57218', '57219', '57220', '57221', '57223', '57224',
       '57225', '57226', '57227', '57231', '57232', '57233', '57234',
       '57235', '57236', '57237', '57238', '57239', '57241', '57242',
       '57243', '57245', '57246', '57247', '57248', '57249', '57251',
       '57252', '57255', '57256', '57257', '57258', '57259', '57260',
       '57261', '57262', '57263', '57264', '57265', '57266', '57268',
       '57269', '57270', '57271', '57272', '57273', '57274', '57276',
       '57278', '57279', '57301', '57311', '57312', '57313', '57314',
       '57315', '57317', '57319', '57321', '57322', '57323', '57324',
       '57325', '57328', '57329', '57330', '57331', '57332', '57334',
       '57335', '57337', '57339', '57340', '57341', '57342', '57344',
       '57345', '57346', '57348', '57349', '57350', '57353', '57354',
       '57355', '57356', '57358', '57359', '57361', '57362', '57363',
       '57364', '57365', '57366', '57367', '57368', '57369', '57370',
       '57371', '57373', '57374', '57375', '57376', '57379', '57380',
       '57381', '57382', '57383', '57384', '57385', '57386', '57401',
       '57402', '57421', '57422', '57424', '57426', '57427', '57428',
       '57429', '57430', '57432', '57433', '57434', '57435', '57436',
       '57437', '57438', '57439', '57440', '57441', '57442', '57445',
       '57446', '57448', '57449', '57450', '57451', '57452', '57454',
       '57455', '57456', '57457', '57460', '57461', '57465', '57466',
       '57467', '57468', '57469', '57470', '57471', '57472', '57473',
       '57474', '57475', '57476', '57477', '57479', '57481', '57501',
       '57520', '57521', '57522', '57523', '57528', '57529', '57531',
       '57532', '57533', '57534', '57536', '57537', '57538', '57540',
       '57541', '57543', '57544', '57547', '57548', '57551', '57552',
       '57553', '57555', '57559', '57560', '57562', '57563', '57564',
       '57566', '57567', '57568', '57569', '57570', '57571', '57572',
       '57574', '57576', '57577', '57579', '57580', '57584', '57585',
       '57601', '57620', '57621', '57622', '57623', '57625', '57626',
       '57630', '57631', '57632', '57633', '57634', '57636', '57638',
       '57639', '57641', '57642', '57644', '57645', '57646', '57648',
       '57649', '57651', '57652', '57656', '57657', '57658', '57659',
       '57660', '57661', '57701', '57702', '57703', '57706', '57709',
       '57714', '57716', '57717', '57718', '57719', '57720', '57722',
       '57724', '57725', '57730', '57732', '57735', '57737', '57738',
       '57741', '57744', '57745', '57747', '57748', '57750', '57751',
       '57752', '57754', '57755', '57756', '57758', '57759', '57760',
       '57761', '57762', '57763', '57764', '57766', '57767', '57769',
       '57770', '57772', '57773', '57775', '57776', '57779', '57780',
       '57782', '57783', '57785', '57787', '57788', '57790', '57791',
       '57792', '57793', '57794', '59319'], dtype=object)

In [8]:
len(df_sd['PHYSICAL ZIP'].unique())

322

In [9]:
df = pd.read_csv('../2_develop_synthetic_company/chaos_one.csv')

In [10]:
df.shape

(27, 12)

In [11]:
df.head()

,Vendor,Company,Street Address,City,State,Country,Zip,1099 Tracking,Phone,Email,Attachments,Open Balance
0,Bob's Burger Joint,NaN,4100 S Ash Grove Ave,Sioux Falls,SD,NaN,57103,NaN,NaN,NaN,NaN,0.00
1,Books by Bessie,Books by Bessie,4101 S Ash Grove Ave,Sioux Falls,SD,NaN,57103,NaN,(650) 555-7745,Books@Intuit.com,NaN,0.00
2,Brosnahan Insurance Agency,Brosnahan Insurance Agency,4200 S Ash Grove Ave,Sioux Falls,SD,NaN,57103,NaN,(650) 555-9912,NaN,NaN,241.23
3,Cal Telephone,Cal Telephone,4201 S Ash Grove Ave,Sioux Falls,SD,NaN,57103,NaN,(650) 555-1616,NaN,NaN,0.00
4,Chin's Gas and Oil,Chin's Gas and Oil,4204 S Ash Grove Ave,Sioux Falls,SD,NaN,57103,NaN,NaN,NaN,NaN,0.00

In [12]:
my_len = df.shape[0]
target_zips = df_sd['PHYSICAL ZIP'].unique()[0:27]

In [13]:
rec_list = []
for my_zip in target_zips:
    print(my_zip)
    df1 = df_sd[df_sd['PHYSICAL ZIP'] == my_zip]
    print(df1['PHYSICAL DELV ADDR'])
    my_rec = df1.iloc[0].to_dict()
    print(my_rec)
    rec_list.append(my_rec)

57001
26118    111 DAKOTA ST
26150    111 DAKOTA ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57001', 'LOCALE NAME': 'ALCESTER', 'PHYSICAL DELV ADDR': '111 DAKOTA ST', 'PHYSICAL CITY': 'ALCESTER', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57001', 'PHYSICAL ZIP 4': '9998'}
57002
26119    219 N BROADWAY ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57002', 'LOCALE NAME': 'AURORA', 'PHYSICAL DELV ADDR': '219 N BROADWAY ST', 'PHYSICAL CITY': 'AURORA', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57002', 'PHYSICAL ZIP 4': '9998'}
57003
26120    132 ST OLAF AVE
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57003', 'LOCALE NAME': 'BALTIC', 'PHYSICAL DELV ADDR': '132 ST OLAF AVE', 'PHYSICAL CITY': 'BALTIC', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57003', 'PHYSICAL ZIP 4': '9998'}
57004
26121    100 S 3RD ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57004', 'LOCALE NAME': 'BERESFORD', 'PHYSICAL DELV ADDR': '100 S 3RD ST', 'PHYSICAL CITY': 'BERESFORD', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57004', 'PHYSICAL ZIP 4': '9998'}
57005
26122    1420 E ASPEN BLVD
26190    1420 E ASPEN BLVD
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57005', 'LOCALE NAME': 'BRANDON', 'PHYSICAL DELV ADDR': '1420 E ASPEN BLVD', 'PHYSICAL CITY': 'BRANDON', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57005', 'PHYSICAL ZIP 4': '9998'}
57006
26123    500 MAIN AVE
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57006', 'LOCALE NAME': 'BROOKINGS', 'PHYSICAL DELV ADDR': '500 MAIN AVE', 'PHYSICAL CITY': 'BROOKINGS', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57006', 'PHYSICAL ZIP 4': '9998'}
57069
26124    16 COURT ST
26192    16 COURT ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57010', 'LOCALE NAME': 'VERMILLION', 'PHYSICAL DELV ADDR': '16 COURT ST', 'PHYSICAL CITY': 'VERMILLION', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57069', 'PHYSICAL ZIP 4': '9998'}
57012
26125    222 W MAIN ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57012', 'LOCALE NAME': 'CANISTOTA', 'PHYSICAL DELV ADDR': '222 W MAIN ST', 'PHYSICAL CITY': 'CANISTOTA', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57012', 'PHYSICAL ZIP 4': '9998'}
57013
26126    315 E 5TH ST
26141    315 E 5TH ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57013', 'LOCALE NAME': 'CANTON', 'PHYSICAL DELV ADDR': '315 E 5TH ST', 'PHYSICAL CITY': 'CANTON', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57013', 'PHYSICAL ZIP 4': '9998'}
57014
26127    533 BROADWAY ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57014', 'LOCALE NAME': 'CENTERVILLE', 'PHYSICAL DELV ADDR': '533 BROADWAY ST', 'PHYSICAL CITY': 'CENTERVILLE', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57014', 'PHYSICAL ZIP 4': '9998'}
57015
26128    224 MAIN ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57015', 'LOCALE NAME': 'CHANCELLOR', 'PHYSICAL DELV ADDR': '224 MAIN ST', 'PHYSICAL CITY': 'CHANCELLOR', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57015', 'PHYSICAL ZIP 4': '9998'}
57039
26129    200 S MAIN ST
26136    200 S MAIN ST
26158    200 S MAIN ST
26202    200 S MAIN ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57015', 'LOCALE NAME': 'LENNOX', 'PHYSICAL DELV ADDR': '200 S MAIN ST', 'PHYSICAL CITY': 'LENNOX', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57039', 'PHYSICAL ZIP 4': '9998'}
57016
26130    410 4TH ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57016', 'LOCALE NAME': 'CHESTER', 'PHYSICAL DELV ADDR': '410 4TH ST', 'PHYSICAL CITY': 'CHESTER', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57016', 'PHYSICAL ZIP 4': '9998'}
57018
26131    213 E 4TH ST
26133    213 E 4TH ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57016', 'LOCALE NAME': 'COLTON', 'PHYSICAL DELV ADDR': '213 E 4TH ST', 'PHYSICAL CITY': 'COLTON', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57018', 'PHYSICAL ZIP 4': '9998'}
57017
26132    129 N MAIN ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57017', 'LOCALE NAME': 'COLMAN', 'PHYSICAL DELV ADDR': '129 N MAIN ST', 'PHYSICAL CITY': 'COLMAN', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57017', 'PHYSICAL ZIP 4': '9998'}
57020
26134    112 MAIN ST
26177    112 MAIN ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57020', 'LOCALE NAME': 'CROOKS', 'PHYSICAL DELV ADDR': '112 MAIN ST', 'PHYSICAL CITY': 'CROOKS', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57020', 'PHYSICAL ZIP 4': '9998'}
57021
26135    110 E US HIGHWAY 18
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57021', 'LOCALE NAME': 'DAVIS', 'PHYSICAL DELV ADDR': '110 E US HIGHWAY 18', 'PHYSICAL CITY': 'DAVIS', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57021', 'PHYSICAL ZIP 4': '9998'}
57022
26137    305 E 4TH ST
26185    305 E 4TH ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57022', 'LOCALE NAME': 'DELL RAPIDS', 'PHYSICAL DELV ADDR': '305 E 4TH ST', 'PHYSICAL CITY': 'DELL RAPIDS', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57022', 'PHYSICAL ZIP 4': '9998'}
57028
26138    102 W 2ND AVE
26143    102 W 2ND AVE
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57024', 'LOCALE NAME': 'FLANDREAU', 'PHYSICAL DELV ADDR': '102 W 2ND AVE', 'PHYSICAL CITY': 'FLANDREAU', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57028', 'PHYSICAL ZIP 4': '9998'}
57025
26139    123 W MAIN ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57025', 'LOCALE NAME': 'ELK POINT', 'PHYSICAL DELV ADDR': '123 W MAIN ST', 'PHYSICAL CITY': 'ELK POINT', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57025', 'PHYSICAL ZIP 4': '9998'}
57026
26140    207 ELK ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57026', 'LOCALE NAME': 'ELKTON', 'PHYSICAL DELV ADDR': '207 ELK ST', 'PHYSICAL CITY': 'ELKTON', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57026', 'PHYSICAL ZIP 4': '9998'}
57027
26142    320 LINCOLN AVE
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57027', 'LOCALE NAME': 'FAIRVIEW', 'PHYSICAL DELV ADDR': '320 LINCOLN AVE', 'PHYSICAL CITY': 'FAIRVIEW', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57027', 'PHYSICAL ZIP 4': '9998'}
57029
26144    421 S POPLAR ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57029', 'LOCALE NAME': 'FREEMAN', 'PHYSICAL DELV ADDR': '421 S POPLAR ST', 'PHYSICAL CITY': 'FREEMAN', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57029', 'PHYSICAL ZIP 4': '9998'}
57030
26145    641 N MAIN AVE
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57030', 'LOCALE NAME': 'GARRETSON', 'PHYSICAL DELV ADDR': '641 N MAIN AVE', 'PHYSICAL CITY': 'GARRETSON', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57030', 'PHYSICAL ZIP 4': '9998'}
57031
26146    508 WASHINGTON ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57031', 'LOCALE NAME': 'GAYVILLE', 'PHYSICAL DELV ADDR': '508 WASHINGTON ST', 'PHYSICAL CITY': 'GAYVILLE', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57031', 'PHYSICAL ZIP 4': '9998'}
57078
26147    506 W 25TH ST
26166    506 W 25TH ST
26189    506 W 25TH ST
26204    506 W 25TH ST
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57031', 'LOCALE NAME': 'YANKTON', 'PHYSICAL DELV ADDR': '506 W 25TH ST', 'PHYSICAL CITY': 'YANKTON', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57078', 'PHYSICAL ZIP 4': '9998'}
57032
26148    518 N CLIFF AVE
Name: PHYSICAL DELV ADDR, dtype: object
{'AREA NAME': 'CENTRAL', 'AREA CODE': '4J', 'DISTRICT NAME': 'IA-NE-SD', 'DISTRICT NO': '500', 'DELIVERY ZIPCODE': '57032', 'LOCALE NAME': 'HARRISBURG', 'PHYSICAL DELV ADDR': '518 N CLIFF AVE', 'PHYSICAL CITY': 'HARRISBURG', 'PHYSICAL STATE': 'SD', 'PHYSICAL ZIP': '57032', 'PHYSICAL ZIP 4': '2729'}

In [14]:
df_a = pd.DataFrame(rec_list)

In [15]:
df_a.head()

,AREA NAME,AREA CODE,DISTRICT NAME,DISTRICT NO,DELIVERY ZIPCODE,LOCALE NAME,PHYSICAL DELV ADDR,PHYSICAL CITY,PHYSICAL STATE,PHYSICAL ZIP,PHYSICAL ZIP 4
0,CENTRAL,4J,IA-NE-SD,500,57001,ALCESTER,111 DAKOTA ST,ALCESTER,SD,57001,9998
1,CENTRAL,4J,IA-NE-SD,500,57002,AURORA,219 N BROADWAY ST,AURORA,SD,57002,9998
2,CENTRAL,4J,IA-NE-SD,500,57003,BALTIC,132 ST OLAF AVE,BALTIC,SD,57003,9998
3,CENTRAL,4J,IA-NE-SD,500,57004,BERESFORD,100 S 3RD ST,BERESFORD,SD,57004,9998
4,CENTRAL,4J,IA-NE-SD,500,57005,BRANDON,1420 E ASPEN BLVD,BRANDON,SD,57005,9998

In [16]:
df_a['AREA NAME'].unique()

array(['CENTRAL'], dtype=object)

In [17]:
df_a.rename(columns={'PHYSICAL ZIP': 'Zip'}, inplace=True)

In [18]:
df_a.rename(columns={'PHYSICAL CITY': 'City'}, inplace=True)

In [19]:
df_a.rename(columns={'PHYSICAL STATE': 'State'}, inplace=True)

In [20]:
df_a.rename(columns={'PHYSICAL DELV ADDR': 'Street Address'}, inplace=True)

In [21]:
df_a.head()

,AREA NAME,AREA CODE,DISTRICT NAME,DISTRICT NO,DELIVERY ZIPCODE,LOCALE NAME,Street Address,City,State,Zip,PHYSICAL ZIP 4
0,CENTRAL,4J,IA-NE-SD,500,57001,ALCESTER,111 DAKOTA ST,ALCESTER,SD,57001,9998
1,CENTRAL,4J,IA-NE-SD,500,57002,AURORA,219 N BROADWAY ST,AURORA,SD,57002,9998
2,CENTRAL,4J,IA-NE-SD,500,57003,BALTIC,132 ST OLAF AVE,BALTIC,SD,57003,9998
3,CENTRAL,4J,IA-NE-SD,500,57004,BERESFORD,100 S 3RD ST,BERESFORD,SD,57004,9998
4,CENTRAL,4J,IA-NE-SD,500,57005,BRANDON,1420 E ASPEN BLVD,BRANDON,SD,57005,9998

In [22]:
df_b = df_a[['Street Address', 'City', 'State', 'Zip']]

In [23]:
df_b.head()

      Street Address       City State    Zip
0      111 DAKOTA ST   ALCESTER    SD  57001
1  219 N BROADWAY ST     AURORA    SD  57002
2    132 ST OLAF AVE     BALTIC    SD  57003
3       100 S 3RD ST  BERESFORD    SD  57004
4  1420 E ASPEN BLVD    BRANDON    SD  57005

In [24]:
df_s = pd.read_csv('../2_develop_synthetic_company/synthetic_one_company.csv')

In [26]:
df_s.shape

(27, 12)

In [27]:
df_s.update(df_b)

In [28]:
df_s.head()

,Vendor,Company,Street Address,City,State,Country,Zip,1099 Tracking,Phone,Email,Attachments,Open Balance
0,Bob's Burger Joint,NaN,111 DAKOTA ST,ALCESTER,SD,NaN,57001,NaN,NaN,NaN,NaN,0.00
1,Books by Bessie,Books by Bessie,219 N BROADWAY ST,AURORA,SD,NaN,57002,NaN,(650) 555-7745,Books@Intuit.com,NaN,0.00
2,Brosnahan Insurance Agency,Brosnahan Insurance Agency,132 ST OLAF AVE,BALTIC,SD,NaN,57003,NaN,(650) 555-9912,NaN,NaN,241.23
3,Cal Telephone,Cal Telephone,100 S 3RD ST,BERESFORD,SD,NaN,57004,NaN,(650) 555-1616,NaN,NaN,0.00
4,Chin's Gas and Oil,Chin's Gas and Oil,1420 E ASPEN BLVD,BRANDON,SD,NaN,57005,NaN,NaN,NaN,NaN,0.00

In [29]:
df_s.to_csv('synthetic_two_company.csv', index = False)