In [1]:
# 11_logic_tester

In [2]:
import pandas as pd

In [3]:
from address_match_proto import is_valid_street_simplea, ret_options

In [4]:
df = pd.read_csv('outliers.csv')

In [5]:
df.head()

,Unnamed: 0,Vendor,Company,Street Address,City,State,Country,Zip,1099 Tracking,Phone,Email,Attachments,Open Balance
0,0,Happy,NaN,410 4TH ST,CHESTER,SD,NaN,57016,NaN,NaN,NaN,NaN,0.0
1,1,Mahoney Mugs,Mahoney Mugs,108 MAIN ST,CROOKS,SD,NaN,57020,NaN,NaN,NaN,NaN,0.0
2,2,Met Life Dental,Met Life Dental,110 E US HIGHWAY 18,DAVIS,SD,NaN,57021,NaN,NaN,NaN,NaN,0.0
3,3,National Eye Care,National Eye Care,305 E 4TH ST,DELL RAPIDS,SD,NaN,57022,NaN,(800) 555-5555,"Nateyecare@intuit.com, pauliejones15@intuit.com",NaN,0.0
4,4,Robertson & Associates,Robertson & Associates,320 LINCOLN AVE,FAIRVIEW,SD,NaN,57027,NaN,(650) 557-1111,NaN,NaN,315.0

In [6]:
def find_longest_word(input_string):
    # Split the input string into words
    words = input_string.split()

    # Find the longest word
    longest_word = max(words, key=len)

    return longest_word

In [7]:
def longest_street_word(df_o, qb_street_address, qb_city, qb_state, qb_zip):
    long_word = find_longest_word(qb_street_address)
    print('LONG:',long_word)
    df_lw = df_o[df_o['street'].str.contains(long_word, case=False, na=False)]
    return df_lw

In [8]:
df_a = df[['Street Address', 'City', 'State', 'Zip']]

In [9]:
for i,r in df_a.iterrows():
    print(r)
    qb_street_address = r['Street Address']
    qb_city = r['City']
    qb_state = r['State']
    qb_zip = r['Zip']
    print('COMPLEX', qb_street_address, qb_city, qb_state, qb_zip)
    df_o = ret_options(qb_street_address, qb_city, qb_state, qb_zip)
    num = df_o.shape[0]
    print(f'it could be any one of {num} options')
    print(df_o.head(num))
    df_l = longest_street_word(df_o, qb_street_address, qb_city, qb_state, qb_zip)
    num1 = df_l.shape[0]
    print(f'it could be any one of {num1} LONG WORD options')
    print(df_l.head(2))

Street Address    410 4TH ST
City                 CHESTER
State                     SD
Zip                    57016
Name: 0, dtype: object
COMPLEX 410 4TH ST CHESTER SD 57016
it could be any one of 0 options
Empty DataFrame
Columns: [id, zipcode, number, street, street2, city, state, latitude, longitude]
Index: []
LONG: 410
it could be any one of 0 LONG WORD options
Empty DataFrame
Columns: [id, zipcode, number, street, street2, city, state, latitude, longitude]
Index: []
Street Address    108 MAIN ST
City                   CROOKS
State                      SD
Zip                     57020
Name: 1, dtype: object
COMPLEX 108 MAIN ST CROOKS SD 57020
it could be any one of 11 options
           id zipcode number      street street2    city state   latitude  \
40  190981681   57020    108    E 7TH ST          CROOKS    SD  43.657254
41  190984823   57020    108    E 8TH ST          CROOKS    SD  43.656341
42  190995531   57020    108  N WEST AVE          CROOKS    SD  43.660260
43  190997579   57020    108   N 1ST AVE          CROOKS    SD  43.660285
44  191023145   57020    108    E 6TH ST          CROOKS    SD  43.658146
45  191024628   57020    108   N 2ND AVE          CROOKS    SD  43.660542
46  191024921   57020    108    E 9TH ST          CROOKS    SD  43.655325
47  191027745   57020    108   S PARK DR          CROOKS    SD  43.659003
48  191029368   57020    108    E 5TH ST          CROOKS    SD  43.659055
49  191154577   57020    108  S ERIC AVE          CROOKS    SD  43.659009
50  191154603   57020    108   E MAIN ST          CROOKS    SD  43.662270

    longitude
40 -96.809964
41 -96.810111
42 -96.810771
43 -96.809447
44 -96.810057
45 -96.808183
46 -96.810120
47 -96.807462
48 -96.810196
49 -96.813540
50 -96.810419
LONG: MAIN
it could be any one of 1 LONG WORD options
           id zipcode number     street street2    city state  latitude  \
50  191154603   57020    108  E MAIN ST          CROOKS    SD  43.66227

    longitude
50 -96.810419
Street Address    110 E US HIGHWAY 18
City                            DAVIS
State                              SD
Zip                             57021
Name: 2, dtype: object
COMPLEX 110 E US HIGHWAY 18 DAVIS SD 57021
it could be any one of 3 options
           id zipcode number         street street2   city state   latitude  \
17  191156030   57021    110  E US HWY 18TH          DAVIS    SD  43.257884
18  191156044   57021    110  W US HWY 18TH          DAVIS    SD  43.257774
19  191156066   57021    110       E 4TH ST          DAVIS    SD  43.258740

    longitude
17 -96.993006
18 -96.994798
19 -96.992643
LONG: HIGHWAY
it could be any one of 0 LONG WORD options
Empty DataFrame
Columns: [id, zipcode, number, street, street2, city, state, latitude, longitude]
Index: []
Street Address    305 E 4TH ST
City               DELL RAPIDS
State                       SD
Zip                      57022
Name: 3, dtype: object
COMPLEX 305 E 4TH ST DELL RAPIDS SD 57022
it could be any one of 8 options
            id zipcode number     street street2         city state  \
690  190986767   57022    305   E 7TH ST          DELL RAPIDS    SD
691  190990081   57022    305  E 10TH ST          DELL RAPIDS    SD
692  190994463   57022    305   E 9TH ST          DELL RAPIDS    SD
693  190995782   57022    305   W 8TH ST          DELL RAPIDS    SD
694  191026008   57022    305  E 11TH ST          DELL RAPIDS    SD
695  191032171   57022    305   E 6TH ST          DELL RAPIDS    SD
696  191046630   57022    305   E 8TH ST          DELL RAPIDS    SD
697  191114542   57022    305   W 3RD ST          DELL RAPIDS    SD

      latitude  longitude
690  43.825976 -96.712795
691  43.828835 -96.712562
692  43.827868 -96.712715
693  43.827375 -96.720717
694  43.829696 -96.712447
695  43.825007 -96.712825
696  43.826904 -96.712759
697  43.822378 -96.721689
LONG: 305
it could be any one of 0 LONG WORD options
Empty DataFrame
Columns: [id, zipcode, number, street, street2, city, state, latitude, longitude]
Index: []
Street Address    320 LINCOLN AVE
City                     FAIRVIEW
State                          SD
Zip                         57027
Name: 4, dtype: object
COMPLEX 320 LINCOLN AVE FAIRVIEW SD 57027
it could be any one of 3 options
           id zipcode number       street street2      city state   latitude  \
39  191093983   57027    320       ELM ST          FAIRVIEW    SD  43.222380
40  191157981   57027    320  LINCOLN AVE          FAIRVIEW    SD  43.221798
41  191157994   57027    320       ASH ST          FAIRVIEW    SD  43.222431

    longitude
39 -96.487736
40 -96.488607
41 -96.489094
LONG: LINCOLN
it could be any one of 1 LONG WORD options
           id zipcode number       street street2      city state   latitude  \
40  191157981   57027    320  LINCOLN AVE          FAIRVIEW    SD  43.221798

    longitude
40 -96.488607
Street Address    506 W 25TH ST
City                    YANKTON
State                        SD
Zip                       57078
Name: 5, dtype: object
COMPLEX 506 W 25TH ST YANKTON SD 57078
it could be any one of 29 options
             id zipcode   number             street street2     city state  \
5667  190923567   57078      506  HIDDEN HOLLOWS DR          YANKTON    SD
5668  191064677   57078      506           MAPLE ST          YANKTON    SD
5669  191064693   57078      506          W 16TH ST          YANKTON    SD
5670  191064996   57078      506           REGAL DR          YANKTON    SD
5671  191065053   57078      506           PEARL ST          YANKTON    SD
5672  191065194   57078      506       APPLEWOOD DR          YANKTON    SD
5673  191065537   57078      506        BURLEIGH ST          YANKTON    SD
5674  191065690   57078      506           GREEN ST          YANKTON    SD
5675  191065952   57078      506          WALNUT ST          YANKTON    SD
5676  191065992   57078      506           W 3RD ST          YANKTON    SD
5677  191079395   57078      506          E 21ST ST          YANKTON    SD
5678  191079576   57078      506           W 8TH ST          YANKTON    SD
5679  191079811   57078      506            PINE ST          YANKTON    SD
5680  191079977   57078      506           W 6TH ST          YANKTON    SD
5681  191080203   57078      506           CEDAR ST          YANKTON    SD
5682  191080498   57078      506          E 11TH ST          YANKTON    SD
5683  191162560   57078      506          E 17TH ST          YANKTON    SD
5684  191162561   57078      506          E 29TH ST          YANKTON    SD
5685  191162562   57078      506           E 5TH ST          YANKTON    SD
5686  191162568   57078      506         BURGESS RD          YANKTON    SD
5687  191162587   57078      506           E 6TH ST          YANKTON    SD
5688  191162588   57078      506           E 8TH ST          YANKTON    SD
5689  191162589   57078      506            LINN ST          YANKTON    SD
5690  191162590   57078      506          LOCUST ST          YANKTON    SD
5691  191162591   57078      506        MULBERRY ST          YANKTON    SD
5692  191162592   57078      506          SPRUCE ST          YANKTON    SD
5693  191162593   57078      506           W 2ND ST          YANKTON    SD
5694  191223969   57078      506          E 10TH ST          YANKTON    SD
5695  191223961   57078  506-1/2           CEDAR ST          YANKTON    SD

       latitude  longitude
5667  42.871400 -97.543363
5668  42.873035 -97.403166
5669  42.884382 -97.398136
5670  42.902179 -97.383200
5671  42.872887 -97.385707
5672  42.903217 -97.384645
5673  42.873017 -97.382693
5674  42.873083 -97.401573
5675  42.872980 -97.393267
5676  42.869949 -97.399114
5677  42.890753 -97.384349
5678  42.876276 -97.399162
5679  42.872898 -97.388828
5680  42.873885 -97.399446
5681  42.872989 -97.395193
5682  42.880020 -97.384713
5683  42.885314 -97.386251
5684  42.904865 -97.386479
5685  42.872408 -97.384938
5686  42.891506 -97.384340
5687  42.873728 -97.384915
5688  42.876430 -97.384882
5689  42.873060 -97.398450
5690  42.873064 -97.400042
5691  42.872769 -97.387226
5692  42.873224 -97.404645
5693  42.868652 -97.399576
5694  42.878937 -97.384700
5695  42.872945 -97.395235
LONG: 25TH
it could be any one of 0 LONG WORD options
Empty DataFrame
Columns: [id, zipcode, number, street, street2, city, state, latitude, longitude]
Index: []